FROM node:18.18.2 AS base
WORKDIR /app

# Rebuild the source code only when needed
FROM base AS builder
ARG NEXT_PUBLIC_NETWORK_TYPE
ARG TELEGRAM_BOT_ID_MAINNET
ARG TELEGRAM_BOT_ID_TESTNET
ENV NEXT_PUBLIC_NETWORK_TYPE=${NEXT_PUBLIC_NETWORK_TYPE}
ENV TELEGRAM_BOT_ID_MAINNET=${TELEGRAM_BOT_ID_MAINNET}
ENV TELEGRAM_BOT_ID_TESTNET=${TELEGRAM_BOT_ID_TESTNET}

# Production image, copy all the files and run next
FROM base AS runner
ARG NEXT_PUBLIC_NETWORK_TYPE
ARG TELEGRAM_BOT_ID_MAINNET
ARG TELEGRAM_BOT_ID_TESTNET
ENV NEXT_PUBLIC_NETWORK_TYPE=${NEXT_PUBLIC_NETWORK_TYPE}
ENV TELEGRAM_BOT_ID_MAINNET=${TELEGRAM_BOT_ID_MAINNET}
ENV TELEGRAM_BOT_ID_TESTNET=${TELEGRAM_BOT_ID_TESTNET}

# COPY . /app/
RUN npm install -g
RUN yarn
RUN yarn build:${NEXT_PUBLIC_NETWORK_TYPE}
ENTRYPOINT yarn start:${NEXT_PUBLIC_NETWORK_TYPE}
EXPOSE 3333