import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useMemo } from "react";
import dynamic from "next/dynamic";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portkey bot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const Provider = useMemo(() => {
    return dynamic(() => import('@/provider'), { ssr: false });
  }, []);
  return (
    <html lang="en">
       <head>
        <Script strategy="beforeInteractive" src="/telegram-web-app.js" />
      </head>
      <body className={inter.className} style={{ backgroundColor: '#531DDC'}}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
